version: '3.8'
services:
  base:
    container_name: data
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: jee
      MYSQL_USER: jeeUser
      MYSQL_PASSWORD: jee
    ports:
      - '3309:3306'
    volumes:
      - ./data:/var/lib/mysql